### Create a new item
POST http://localhost:3000/v1/category
Content-Type: application/json

{
  "name": "Shoes",
  "slug": "shoes",
  "use_in_menu": true
}  

### Get all items
GET http://localhost:3000/v1/category/search

### Get a specific item by ID
GET http://localhost:3000/v1/category/1

### Update an item by ID
PUT http://localhost:3000/v1/category/1
Content-Type: application/json

{
   "name": "Shoes",
    "slug": "shoes"
}

### Delete an item by ID
DELETE http://localhost:3000/v1/category/2